"""Write the paper's numbers, tables and plot data from the locked results.

    uv run python paper/make_data.py

Reads `reports/results/*.csv`, `reports/physics_check.md`, the replay files in `models/replays/`
and the saved held-out predictions, and writes `paper/data/`: `results.tex` (one macro per
number quoted in the text), `*.tex` table rows and `*.csv` plot data. Nothing in the paper is
typed by hand, so the paper cannot drift from the results; `tests/test_paper_data.py` checks
that the committed files match a fresh run.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from collections.abc import Callable
from pathlib import Path

import pandas as pd

from keyframe import paths

PAPER = Path(__file__).resolve().parent
LOADS = (40, 60, 75, 85)
LOAD_WORD = {40: "Forty", 60: "Sixty", 75: "SeventyFive", 85: "EightyFive"}
FAULTS = ["AC", "AF", "INJ", "CW", "TD"]
CLASSES = ["Normal", *FAULTS]
FAULT_NAME = {
    "Normal": "Normal running",
    "AC": "Air cooler fouling",
    "AF": "Air filter clogging",
    "INJ": "Injector nozzle clogging",
    "CW": "Cooling water pump cavitation",
    "TD": "Turbine degradation",
}
RUN_FAULT = {
    "AC_Fouling": "AC",
    "AF_Clogging": "AF",
    "CW_Pump_Cavitation": "CW",
    "Turbine_Degradation": "TD",
}
MODEL_NAME = {
    "logreg": "Logistic regression",
    "logistic_regression": "Logistic regression",
    "random_forest": "Random forest",
    "lightgbm": "LightGBM",
    "xgboost": "XGBoost",
    "dummy_majority": "Majority class",
}
GROUPS = ["air path", "fuel system", "cooling", "lube oil", "combustion and power"]


def f(x: float, digits: int = 3) -> str:
    return f"{x:.{digits}f}"


def pct(x: float, digits: int = 1) -> str:
    return f"{100 * x:.{digits}f}"


def delay(seconds: float) -> str:
    s = int(round(seconds))
    m, s = divmod(s, 60)
    return f"{m}\\,min {s}\\,s" if m else f"{s}\\,s"


def results(name: str) -> pd.DataFrame:
    return pd.read_csv(paths.RESULTS / f"{name}.csv")


class Macros:
    """Collects `\\newcommand` definitions; names must be letters only (TeX rule)."""

    def __init__(self) -> None:
        self.items: dict[str, str] = {}

    def __setitem__(self, name: str, value: str) -> None:
        if not re.fullmatch(r"[A-Za-z]+", name):
            raise ValueError(f"macro name {name!r} must be letters only")
        if name in self.items:
            raise ValueError(f"macro {name} defined twice")
        self.items[name] = value

    def text(self) -> str:
        lines = ["% Generated by paper/make_data.py from the locked results. Do not edit."]
        lines += [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in self.items.items()]
        return "\n".join(lines) + "\n"


def data_section(m: Macros) -> None:
    rows = results("00_row_counts")
    lockbox = results("07_lockbox")
    lock_rows = int(lockbox.loc[lockbox["scope"] == "all", "n_rows"].iloc[0])
    reference = int(rows.loc[rows["run"] == "Reference_Data", "data_rows"].iloc[0])
    total = int(rows["data_rows"].sum())
    m["DataRowsModelling"] = f"{total:,}"
    m["DataRowsAll"] = f"{total + lock_rows:,}"
    m["DataRowsReference"] = f"{reference:,}"
    m["DataRowsLockbox"] = f"{lock_rows:,}"
    m["DataFaultRuns"] = str(len(rows) - 1)
    switch = results("00_switch_on_points").dropna(subset=["t"])
    m["DataHealthyMinMin"] = f"{switch['healthy_minutes'].min():.0f}"
    m["DataHealthyMinMax"] = f"{switch['healthy_minutes'].max():.0f}"
    m["DataFaultyMinMin"] = f"{switch['faulty_minutes'].min():.0f}"
    m["DataFaultyMinMax"] = f"{switch['faulty_minutes'].max():.0f}"
    m["DataRunsWithSwitchOn"] = str(len(switch))


def coverage_table() -> str:
    cov = results("01_coverage").set_index("fault_type")
    lines = []
    for fault in FAULTS:
        cells = [
            f"{int(cov.loc[fault, str(load)]):,}" if cov.loc[fault, str(load)] else "--"
            for load in LOADS
        ]
        lines.append(f"{FAULT_NAME[fault]} & " + " & ".join(cells) + r" \\")
    return "\n".join(lines) + "\n"


def exported_model(m: Macros) -> None:
    meta = json.loads((paths.MODELS / "model_meta.json").read_text())
    m["FeatCount"] = str(meta["n_features"])
    m["ExportAlarmDuration"] = f"{meta['alarm']['min_duration_s']:.0f}"
    m["ExportAlarmProbability"] = f"{meta['alarm']['min_probability']:.1f}"


def baselines(m: Macros) -> None:
    base = results("02_baselines")
    pooled = base[base["fold"] == "pooled"].set_index("model")
    m["BaseMajority"] = f(pooled.loc["dummy_majority", "macro_f1"])
    m["BaseLogreg"] = f(pooled.loc["logistic_regression", "macro_f1"])
    m["BaseLogregFar"] = pct(pooled.loc["logistic_regression", "false_alarm_rate"])
    m["BaseLightgbm"] = f(pooled.loc["lightgbm", "macro_f1"])
    m["BaseForest"] = f(pooled.loc["random_forest", "macro_f1"])


ABLATION_SETS = [
    ("raw", "Raw readings"),
    ("raw+physics", "Raw + physics"),
    ("raw+physics+rolling", "Raw + physics + rolling"),
    ("residuals", "Residuals"),
    ("residuals+physics", "Residuals + physics"),
    ("residuals+physics+rolling", "Residuals + physics + rolling"),
]


def ablation(m: Macros) -> str:
    table = results("03_ablation")
    pooled = table[table["fold"] == "pooled"].drop_duplicates(["feature_set", "model"])
    pooled = pooled.set_index(["feature_set", "model"])
    best = pooled["macro_f1"].max()
    lines = []
    for key, label in ABLATION_SETS:
        cells = []
        for model in ("logreg", "lightgbm"):
            row = pooled.loc[(key, model)]
            score = f(row["macro_f1"])
            cells += [
                f"\\textbf{{{score}}}" if row["macro_f1"] == best else score,
                pct(row["false_alarm_rate"]),
            ]
        lines.append(f"{label} & " + " & ".join(cells) + r" \\")
    m["AblRaw"] = f(pooled.loc[("raw", "lightgbm"), "macro_f1"])
    m["AblPhysics"] = f(pooled.loc[("raw+physics", "lightgbm"), "macro_f1"])
    m["AblRolling"] = f(pooled.loc[("raw+physics+rolling", "lightgbm"), "macro_f1"])
    m["AblRollingFar"] = pct(pooled.loc[("raw+physics+rolling", "lightgbm"), "false_alarm_rate"])
    m["AblResidualBest"] = f(pooled.loc[("residuals+physics", "logreg"), "macro_f1"])
    pruning = results("03_pruning")
    m["AblPruned"] = f(pruning.loc[pruning["fold"] == "pooled", "macro_f1"].iloc[0])
    shop = results("03_shop_test")
    shop = shop[shop["fold"] == "pooled"].set_index("run")
    m["AblShopMain"] = f(shop.loc["main", "macro_f1"])
    m["AblShopTest"] = f(shop.loc["shop_test", "macro_f1"])
    return "\n".join(lines) + "\n"


def models(m: Macros) -> str:
    table = results("04_models")
    pooled = table[table["fold"] == "pooled"].drop_duplicates("model").set_index("model")
    pooled = pooled.sort_values("macro_f1", ascending=False)
    lines = []
    for model, row in pooled.iterrows():
        name = MODEL_NAME[str(model)]
        score = f(row["macro_f1"])
        if model == "xgboost":
            name, score = f"\\textbf{{{name}}}", f"\\textbf{{{score}}}"
        lines.append(
            f"{name} & {score} & {f(row['accuracy'])} & {pct(row['false_alarm_rate'])} & "
            f"{f(row['worst_recall'])} ({row['worst_recall_class']})" + r" \\"
        )
    m["ModelsSecond"] = f(pooled["macro_f1"].iloc[1])
    return "\n".join(lines) + "\n"


def best_model(m: Macros) -> str:
    best = results("04_best_model")
    pooled = best[best["fold"] == "pooled"].iloc[0]
    m["ResFOne"] = f(pooled["macro_f1"])
    m["ResAccuracy"] = f(pooled["accuracy"])
    m["ResFar"] = pct(pooled["false_alarm_rate"])
    m["ResWorstRecall"] = f(pooled["worst_recall"])
    folds = best[best["fold"] != "pooled"].copy()
    folds["fold"] = folds["fold"].astype(int)
    folds = folds.set_index("fold")
    hyper = []
    trials = {
        load: json.loads((paths.MODELS / "tuning" / f"xgboost_fold{load}.json").read_text())[
            "n_trials"
        ]
        for load in LOADS
    }
    m["TuneTrialsMin"] = str(min(trials.values()))
    m["TuneTrialsMax"] = str(max(trials.values()))
    for load in LOADS:
        row = folds.loc[load]
        m[f"FoldF{LOAD_WORD[load]}"] = f(row["macro_f1"])
        m[f"FoldFar{LOAD_WORD[load]}"] = pct(row["false_alarm_rate"])
        hyper.append(
            f"{load}\\,\\% & {row['learning_rate']:.4f} & {int(row['n_estimators'])} & "
            f"{int(row['max_depth'])} & {row['subsample']:.2f} & {row['colsample_bytree']:.2f} & "
            f"{trials[load]} & {f(row['macro_f1'])}" + r" \\"
        )
    m["FoldSpreadMin"] = f(folds["macro_f1"].min())
    m["FoldSpreadMax"] = f(folds["macro_f1"].max())
    first = results("04_first_10_min").set_index("scope")
    m["ResFOneAfterTen"] = f(first.loc["excluding first 10 min after switch-on", "macro_f1"])
    return "\n".join(hyper) + "\n"


def alarms(m: Macros) -> tuple[str, str]:
    table = results("04_alarms")
    xgb = table[table["model"] == "xgboost"]
    settings = xgb.drop_duplicates("fold").set_index("fold")
    setting_rows = []
    for load in LOADS:
        row = settings.loc[load]
        setting_rows.append(
            f"{load}\\,\\% & {int(row['min_duration_s'])} & {row['min_probability']:.1f} & "
            f"{pct(row['false_alarm_rate'])}" + r" \\"
        )
    detected = xgb.dropna(subset=["delay_s"])
    m["AlarmRuns"] = str(len(xgb))
    m["AlarmDetected"] = str(len(detected))
    m["AlarmMissed"] = str(len(xgb) - len(detected))
    m["AlarmMedian"] = delay(detected["delay_s"].median())
    m["AlarmMedianS"] = f"{detected['delay_s'].median():.0f}"
    m["AlarmFastest"] = delay(detected["delay_s"].min())
    m["AlarmSlowest"] = delay(detected["delay_s"].max())
    rows = []
    order = {k: i for i, k in enumerate(FAULTS)}
    xgb = xgb.assign(
        fault=xgb["run"].map(lambda r: RUN_FAULT[r.rsplit("_", 2)[0]]),
        load=xgb["run"].map(lambda r: int(r.rsplit("_", 2)[1])),
    ).sort_values(["fault", "load"], key=lambda s: s.map(order) if s.name == "fault" else s)
    for _, row in xgb.iterrows():
        if pd.isna(row["delay_s"]):
            cell = "no alarm"
        else:
            cell = delay(row["delay_s"])
            if row["class"] != row["fault"]:
                cell += f" (reads {FAULT_NAME[row['class']].lower()})"
        rows.append(f"{FAULT_NAME[row['fault']]} & {row['load']}\\,\\% & {cell}" + r" \\")
    return "\n".join(setting_rows) + "\n", "\n".join(rows) + "\n"


def anomaly(m: Macros) -> str:
    table = results("05_anomaly")
    pooled = table[table["fold"] == "pooled"].set_index(["detector", "inputs"])
    lines = []
    for detector, label in (
        ("pca", "PCA reconstruction"),
        ("iforest", "Isolation forest"),
        ("autoencoder", "Autoencoder"),
    ):
        raw, res = pooled.loc[(detector, "raw")], pooled.loc[(detector, "residual")]
        lines.append(
            f"{label} & {f(raw['auroc'])} & {f(res['auroc'])} & {f(res['auroc_INJ'])} & {f(res['auroc_CW'])}"
            + r" \\"
        )
    targets = results("05_targets")
    headline = targets[targets["metric"].str.startswith("Fault detection AUROC")].iloc[0]
    m["AnomAuroc"] = f(headline["value"])
    return "\n".join(lines) + "\n"


def calibration(m: Macros) -> str:
    table = results("07_calibration").set_index("fold")
    m["CalEce"] = f(table["pooled_ece_before"].iloc[0])
    lines = []
    for load in LOADS:
        row = table.loc[load]
        lines.append(
            f"{load}\\,\\% & {f(row['ece_before'])} & {row['temperature']:.2f} & {f(row['ece_after'])}"
            + r" \\"
        )
    m["CalEceEightyFive"] = f(table.loc[85, "ece_before"])
    return "\n".join(lines) + "\n"


def lockbox(m: Macros) -> None:
    table = results("07_lockbox")
    allrow = table[table["scope"] == "all"].iloc[0]
    m["LockShare"] = f"{100 * allrow['share']:.0f}"
    m["LockLabel"] = FAULT_NAME[allrow["label"]].lower()


def physics(m: Macros) -> str:
    text = (paths.REPORTS / "physics_check.md").read_text()
    result = re.search(r"Result: (\d) of 5 faults pass", text)
    assert result, "physics check result line not found"
    m["PhysPassed"] = result.group(1)
    lines = []
    for fault in FAULTS:
        row = re.search(rf"^\| {fault} \|(.+)$", text, flags=re.M)
        assert row, f"physics check row for {fault} not found"
        cells = [c.strip() for c in row.group(1).split("|")]
        match, day, passed = cells[2], cells[3], cells[4]
        day_word = "yes" if "Yes" in day else "no"
        pass_word = "\\textbf{pass}" if "Yes" in passed else "fail"
        lines.append(f"{FAULT_NAME[fault]} & {match} & {day_word} & {pass_word}" + r" \\")
    return "\n".join(lines) + "\n"


def grouped_shap() -> str:
    table = results("06_grouped_shap").set_index("Unnamed: 0")
    lines = []
    for group in GROUPS:
        cells = []
        for cls in FAULTS:
            value = float(table.loc[group, cls])
            text = "0.00" if round(value, 2) == 0 else f"{value:+.2f}".replace("-", "$-$")
            top = table.loc[GROUPS, cls].astype(float).idxmax() == group
            cells.append(f"\\textbf{{{text}}}" if top else text)
        lines.append(f"{group.capitalize()} & " + " & ".join(cells) + r" \\")
    return "\n".join(lines) + "\n"


def crosscheck(m: Macros) -> None:
    table = results("06_crosscheck")
    m["CrossMin"] = f"{table['spearman_r'].min():.2f}"
    m["CrossMax"] = f"{table['spearman_r'].max():.2f}"


def sensitivity(m: Macros) -> str:
    table = results("07_sensitivity")
    m["SensDropped"] = str(int(table["n_features_dropped"].iloc[0]))
    f1 = table[table["metric"] == "macro_f1"].set_index("fold")
    csv = ["load,headline,no_day"]
    for load in LOADS:
        row = f1.loc[load]
        m[f"SensF{LOAD_WORD[load]}"] = f(row["no_day_channels"])
        csv.append(f"{load},{row['headline']:.4f},{row['no_day_channels']:.4f}")
    cw = table[(table["metric"] == "recall_CW") & (table["fold"] == 60)].iloc[0]
    m["SensCwBefore"] = f"{cw['headline']:.2f}"
    m["SensCwAfter"] = f"{cw['no_day_channels']:.2f}"
    af = table[(table["metric"] == "recall_AF") & (table["fold"] == 40)].iloc[0]
    m["SensAfBefore"] = f"{af['headline']:.2f}"
    m["SensAfAfter"] = f"{af['no_day_channels']:.2f}"
    return "\n".join(csv) + "\n"


def latency(m: Macros) -> None:
    table = results("11_latency").set_index("endpoint")
    m["LatPredict"] = f"{table.loc['/predict', 'median_ms']:.0f}"
    m["LatExplain"] = f"{table.loc['/explain', 'median_ms']:.0f}"
    m["LatWindow"] = str(int(table.loc["/explain", "window_rows"]))


def confusion() -> str:
    preds = pd.read_parquet(paths.PROCESSED / "experiments" / "modelling_xgboost.parquet")
    counts = pd.crosstab(preds["y_true"], preds["y_pred"]).reindex(
        index=CLASSES, columns=CLASSES, fill_value=0
    )
    share = counts.div(counts.sum(axis=1), axis=0)
    lines = []
    for true in CLASSES:
        cells = []
        for pred in CLASSES:
            p = float(share.loc[true, pred])
            # Tint capped at 60% so the dark figures stay readable on every cell.
            shade = int(round(p * 60))
            colour = f"\\cellcolor{{accent!{shade}}}" if shade else ""
            cells.append(f"{colour}{p:.2f}")
        lines.append(f"{FAULT_NAME[true]} & " + " & ".join(cells) + r" \\")
    return "\n".join(lines) + "\n"


def replay_trace(m: Macros) -> str:
    replay = json.loads((paths.MODELS / "replays" / "AC_Fouling_75_Load.json").read_text())
    t0 = replay["frames"][0]["t"]
    switch_on = replay["switch_on_t"]
    alarm_t = next(fr["t"] for fr in replay["frames"] if fr["alarm"] != "Normal")
    m["ReplaySwitchMin"] = f"{(switch_on - t0) / 60:.1f}"
    m["ReplayAlarmMin"] = f"{(alarm_t - t0) / 60:.1f}"
    m["ReplayDelay"] = delay(alarm_t - switch_on)
    lines = ["t_min,temp_c,p_ac,p_normal"]
    for fr in replay["frames"]:
        temp = fr["sensors"]["charge_air_temp_after_cooler"]["value"]
        lines.append(
            f"{(fr['t'] - t0) / 60:.3f},{temp:.3f},{fr['probabilities']['AC']:.4f},{fr['probabilities']['Normal']:.4f}"
        )
    return "\n".join(lines) + "\n"


def switch_on_trace() -> str:
    clean = pd.read_parquet(
        paths.PROCESSED / "clean.parquet",
        columns=["run", "t", "label", "Charge Air IC Air Temp. Out"],
    )
    columns = {}
    for load in LOADS:
        run = clean[clean["run"] == f"AC_Fouling_{load}_Load"].sort_values("t")
        switch_on = run.loc[run["label"] != "Normal", "t"].min()
        minutes = (run["t"] - switch_on) / 60
        window = run[(minutes >= -30) & (minutes <= 60)]
        # One point per 30 s keeps the plot light without changing its shape.
        binned = window.groupby(((window["t"] - switch_on) // 30) * 0.5)[
            "Charge Air IC Air Temp. Out"
        ].mean()
        columns[f"l{load}"] = binned
    frame = pd.DataFrame(columns).sort_index()
    frame.index.name = "t_min"
    return frame.to_csv(float_format="%.3f", na_rep="nan")


def test_counts() -> str:
    """Counts of the automated tests, collected (not run) at generation time."""
    out = subprocess.run(
        ["uv", "run", "pytest", "--collect-only", "-q", "-p", "no:warnings"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    # The project's addopts make -q print one "file: count" line per test file.
    per_file = [int(n) for n in re.findall(r"^tests/\S+: (\d+)$", out, flags=re.M)]
    total = re.search(r"(\d+) tests? collected", out)
    python = sum(per_file) if per_file else int(total.group(1)) if total else 0
    if python == 0:
        raise RuntimeError(f"could not count the Python tests from:\n{out[-500:]}")
    web = subprocess.run(
        ["npx", "vitest", "list", "--json"],
        cwd=paths.ROOT / "web",
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    web_count = len(json.loads(web))
    m = Macros()
    m["TestsPython"] = str(python)
    m["TestsWeb"] = str(web_count)
    return m.text()


def build(out: Path, counts: bool = True) -> list[Path]:
    out.mkdir(parents=True, exist_ok=True)
    m = Macros()
    data_section(m)
    exported_model(m)
    baselines(m)
    lockbox(m)
    crosscheck(m)
    latency(m)
    writers: dict[str, Callable[[], str]] = {
        "coverage.tex": coverage_table,
        "ablation.tex": lambda: ablation(m),
        "models.tex": lambda: models(m),
        "anomaly.tex": lambda: anomaly(m),
        "calibration.tex": lambda: calibration(m),
        "physics.tex": lambda: physics(m),
        "grouped_shap.tex": grouped_shap,
        "sensitivity.csv": lambda: sensitivity(m),
        "confusion.tex": confusion,
        "replay_ac75.csv": lambda: replay_trace(m),
        "switchon_ac.csv": switch_on_trace,
    }
    written = []
    for name, writer in writers.items():
        (out / name).write_text(writer())
        written.append(out / name)
    hyper = best_model(m)
    settings, per_run = alarms(m)
    for name, text in (
        ("hyperparameters.tex", hyper),
        ("alarm_settings.tex", settings),
        ("alarms.tex", per_run),
    ):
        (out / name).write_text(text)
        written.append(out / name)
    (out / "results.tex").write_text(m.text())
    written.append(out / "results.tex")
    if counts:
        (out / "counts.tex").write_text(test_counts())
        written.append(out / "counts.tex")
    return written


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=PAPER / "data")
    parser.add_argument("--no-counts", action="store_true", help="skip collecting test counts")
    args = parser.parse_args()
    for path in build(args.out, counts=not args.no_counts):
        print(path.relative_to(paths.ROOT) if path.is_relative_to(paths.ROOT) else path)


if __name__ == "__main__":
    main()
